// Catalog ported from backend/src/data/models.json. Keep bundled entries in sync.
package cli

var managementBundledModels = []Object{
	Object{"id": "Qwen/Qwen3-0.6B", "name": "Qwen3 0.6B", "description": "Tiny model ideal for development, testing, and edge deployments", "size": "0.6B", "task": "text-generation", "conversational": true, "contextLength": 32768, "supportedEngines": []any{"vllm", "sglang", "trtllm"}, "minGpuMemory": "4GB", "minGpus": 1},
	Object{"id": "google/gemma-3-1b-it", "name": "Gemma 3 1B Instruct", "description": "Google's lightweight instruction-tuned model with strong efficiency", "size": "1B", "task": "text-generation", "conversational": true, "contextLength": 32768, "supportedEngines": []any{"vllm", "sglang"}, "minGpuMemory": "4GB", "minGpus": 1, "gated": true},
	Object{"id": "microsoft/Phi-4-mini-instruct", "name": "Phi-4 Mini Instruct", "description": "Microsoft's efficient 3.8B model with 128K context and multilingual support", "size": "3.8B", "task": "text-generation", "conversational": true, "contextLength": 131072, "supportedEngines": []any{"vllm", "sglang"}, "minGpuMemory": "8GB", "minGpus": 1},
	Object{"id": "Qwen/Qwen3-4B", "name": "Qwen3 4B", "description": "Compact model with thinking and non-thinking modes for versatile tasks", "size": "4B", "task": "text-generation", "conversational": true, "contextLength": 32768, "supportedEngines": []any{"vllm", "sglang", "trtllm"}, "minGpuMemory": "10GB", "minGpus": 1},
	Object{"id": "google/gemma-3-4b-it", "name": "Gemma 3 4B Instruct", "description": "Google's multimodal model with 128K context and image understanding", "size": "4B", "task": "image-text-to-text", "conversational": true, "contextLength": 131072, "supportedEngines": []any{"vllm", "sglang"}, "minGpuMemory": "10GB", "minGpus": 1, "gated": true},
	Object{"id": "Qwen/Qwen3-8B", "name": "Qwen3 8B", "description": "Strong all-around model with dynamic reasoning for complex tasks", "size": "8B", "task": "text-generation", "conversational": true, "contextLength": 32768, "supportedEngines": []any{"vllm", "sglang", "trtllm"}, "minGpuMemory": "18GB", "minGpus": 1},
	Object{"id": "deepseek-ai/DeepSeek-R1-Distill-Llama-8B", "name": "DeepSeek R1 Distill 8B", "description": "Reasoning-focused distilled model with strong analytical capabilities", "size": "8B", "task": "text-generation", "conversational": true, "contextLength": 16384, "supportedEngines": []any{"vllm", "sglang"}, "minGpuMemory": "18GB", "minGpus": 1},
	Object{"id": "mistralai/Ministral-3-8B-Instruct-2512-BF16", "name": "Ministral 3 8B Instruct", "description": "Mistral's latest 8B model with 256K context, vision, and function calling", "size": "8B", "task": "image-text-to-text", "conversational": true, "contextLength": 262144, "supportedEngines": []any{"vllm", "sglang"}, "minGpuMemory": "18GB", "minGpus": 1},
	Object{"id": "kaito/llama3.2-1b", "name": "Llama 3.2 1B (GGUF)", "description": "Compact GGUF model for CPU inference - edge deployments", "size": "1B", "task": "text-generation", "conversational": true, "supportedEngines": []any{"llamacpp"}, "license": "Llama", "minGpus": 0},
	Object{"id": "kaito/llama3.2-3b", "name": "Llama 3.2 3B (GGUF)", "description": "Efficient GGUF model for CPU inference - general tasks", "size": "3B", "task": "text-generation", "conversational": true, "supportedEngines": []any{"llamacpp"}, "license": "Llama", "minGpus": 0},
	Object{"id": "kaito/llama3.1-8b", "name": "Llama 3.1 8B (GGUF)", "description": "Balanced GGUF model for CPU inference - performance and efficiency", "size": "8B", "task": "text-generation", "conversational": true, "supportedEngines": []any{"llamacpp"}, "license": "Llama", "minGpus": 0},
	Object{"id": "kaito/llama3.3-70b", "name": "Llama 3.3 70B (GGUF)", "description": "High-performance GGUF model - requires significant memory", "size": "70B", "task": "text-generation", "conversational": true, "supportedEngines": []any{"llamacpp"}, "license": "Llama", "minGpus": 0},
	Object{"id": "kaito/mixtral-8x7b", "name": "Mixtral 8x7B (GGUF)", "description": "Mixture of experts GGUF model for CPU inference", "size": "8x7B", "task": "text-generation", "conversational": true, "supportedEngines": []any{"llamacpp"}, "license": "Apache", "minGpus": 0},
	Object{"id": "kaito/phi4-14b", "name": "Phi 4 14B (GGUF)", "description": "Microsoft research model in GGUF format for CPU inference", "size": "14B", "task": "text-generation", "conversational": true, "supportedEngines": []any{"llamacpp"}, "license": "MIT", "minGpus": 0},
	Object{"id": "kaito/gemma2-2b", "name": "Gemma 2 2B (GGUF)", "description": "Google lightweight GGUF model for CPU inference", "size": "2B", "task": "text-generation", "conversational": true, "supportedEngines": []any{"llamacpp"}, "license": "Gemma", "minGpus": 0},
	Object{"id": "kaito/qwq-32b", "name": "QwQ 32B (GGUF)", "description": "Reasoning-focused GGUF model for CPU inference", "size": "32B", "task": "text-generation", "conversational": true, "supportedEngines": []any{"llamacpp"}, "license": "Apache 2.0", "minGpus": 0},
	Object{"id": "kaito/codestral-22b", "name": "Codestral 22B (GGUF)", "description": "Code generation specialist in GGUF format", "size": "22B", "task": "text-generation", "conversational": true, "supportedEngines": []any{"llamacpp"}, "license": "MNLP", "minGpus": 0},
	Object{"id": "kaito/gpt-oss-20b", "name": "GPT-OSS 20B (GGUF)", "description": "Open source GPT-style GGUF model for CPU inference", "size": "20B", "task": "text-generation", "conversational": true, "supportedEngines": []any{"llamacpp"}, "license": "Apache 2.0", "minGpus": 0},
}
